export const TILES = [
  //technology
  { id: "typescript" },
  { id: "frontend" },
  { id: "backend" },
  { id: "github" },
  { id: "react" },
  { id: "serverless" },
  { id: "resume" },
  { id: "remote" },

  // places and things
  { id: "mountain" },
  { id: "beach" },
  { id: "bluegrass" },
  { id: "airstream" },
  { id: "dog" },
  { id: "he" },
  { id: "they" },
  { id: "Utah" },
  { id: "Virginia" },
  { id: "Philadelphia" },

  // verbs
  { id: "mentored" },
  { id: "traveled" },
  { id: "worked" },
  { id: "studied" },
  { id: "created" },
  { id: "built" },
  { id: "test" },

  // joiner words
  { id: "who" },
  { id: "me" },
  { id: "in" },
  { id: "what" },
  { id: "is" },
  { id: "it" },
  { id: "for" },
  { id: "to" },
  { id: "of" },
  { id: "and" },
  { id: "in" },
  { id: "the" },
  { id: "at" },
  { id: "a" },
  { id: "with" },
  { id: "how" },
  { id: "while" },
  { id: "isn't" },
  { id: "not" },
  { id: "aren't" },
];
